[MASSEMBLY-939] - Line Aggregation Handlers support <updateOnly>
apache/maven-assembly-plugin pull request #32
Opened 2020-07-16 01:47 UTC by roxspring

- Add test for line aggregating behaviour
- Line aggregating handler uses latest lastModified date and supporting `<updateOnly>`
- FileSelectors are always passed PlexusIoResource instances so that lastModified date is available

Following this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MASSEMBLY) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MASSEMBLY-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MASSEMBLY-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

2024-12-12 14:00 UTC, elharo requested changes

2024-12-12 14:00 UTC, elharo commented on src/main/java/org/apache/maven/plugins/assembly/archive/archiver/AssemblyProxyArchiver.java
> +                final FileInfo fileInfo;
use a larger try block, don't split initialization and declaration

2024-12-12 14:00 UTC, elharo commented on src/test/java/org/apache/maven/plugins/assembly/filter/SimpleAggregatingDescriptorHandlerTest.java
> +/*
license above package

2025-06-17 23:11 UTC, jira-importer commented
Resolve #1145

2026-08-25 13:59 UTC, elharo commented
abandoned

2026-08-25 13:59 UTC, closed without merging